global:
  imagePullPolicy: IfNotPresent
  capacityConfig:
    overall: 100
    serviceLevel: ''
    default: 100
  servicePorts:
      perfInfoHttp: 5905
  containerPorts:
      monitoringHttp: 9000
      perfInfoHttp: 5905
  k8sResource:
    container:
      prefix:
      suffix:
  metricPrefix: ''
  metricSuffix: ''
  customExtension:
    allResources:
      labels: {}
      annotations: {}

    lbServices:
      labels: {}
      annotations: {}
    lbDeployments:
      labels: {}
      annotations: {}

    nonlbServices:
      labels: {}
      annotations: {}
    nonlbDeployments:
      labels: {}
      annotations: {}
  cncMetricsName: cnc-metrics
  exposeObservabilityAtService: false
  diamGatewayEnable: false
  multipleIgwEnabled: false

  configServerFullNameOverride: occnp-config-server
  configServerPort: 80
  logStorage: 0 #default calculated value 70
  crictlStorage: 0 #default calculated value 1
  #Resource Values for Hook Jobs
  hookJobResources:
     limits:
       cpu: 2
       memory: 2Gi
     requests:
       cpu: 1
       memory: 1Gi
  
  # Following variables could be replaced from one-click-cnpolicy process
  dbHookImageVersion: &dbHookImageVersion '23.2.2'
  debugToolsImageVersion: &debugToolsImageVersion '23.2.0'

  # ******** Debug tools ********
  #**************************************************************************

  debugTools:
    image: "ocdebug-tools"
    imageTag: *debugToolsImageVersion

  # Allowed Values: DISABLED, ENABLED
  # Preference is to set  "resources" request and limit to same values to avoid HPA issues.
  extraContainers: DISABLED
  debugToolContainerMemoryLimit: 4Gi
  extraContainersVolumesTpl: |
    - name: debug-tools-dir
      emptyDir:
        medium: Memory
        sizeLimit: {{ .Values.global.debugToolContainerMemoryLimit | quote }}
  extraContainersTpl: |
      - command:
          - /bin/sleep
          - infinity
        image: {{ .Values.global.dockerRegistry }}/{{ .Values.global.debugTools.image }}:{{ .Values.global.debugTools.imageTag }}
        imagePullPolicy: IfNotPresent
        name: {{ printf "%s-tools-%s" (include "getprefix" .) (include "getsuffix" .) | trunc 63 | trimPrefix "-" | trimSuffix "-"  }}
        resources:
          requests:
            ephemeral-storage: "512Mi"
            cpu: "0.5"
            memory:  {{ .Values.global.debugToolContainerMemoryLimit | quote }}
          limits:
            ephemeral-storage: "512Mi"
            cpu: "0.5"
            memory: {{ .Values.global.debugToolContainerMemoryLimit | quote }}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_RAW
            - NET_ADMIN
          runAsUser: 7000
        volumeMounts:
        - mountPath: /tmp/tools
          name: debug-tools-dir
          
  tolerations: []
  k8sResources:
    pdb:
      supportedVersions:
        - policy/v1
        - policy/v1beta1

image: occnp/oc-perf-info
imageTag: 23.2.0
replicas: 2
nodeSelectorEnabled: false
nodeSelectorKey: zone
useLbLabelsAndAnnotations: false
helmBasedConfigurationNodeSelectorApiVersion: "v1"
envMysqlDatabase: ''
envLeaderElectionTableName: leader_election
leaderElectionHeartbeatInterval: 2  # float number in seconds
leaderElectionHeartbeatTimeout: 8   # float number in seconds
maxUnavailable: '20%'
pdbMaxUnavailable: ''

service:
  type: ClusterIP
  
  customExtension:
    labels: {}
    annotations: {}

deployment:
  customExtension:
    labels: {}
    annotations: {}

configmapPerformance:
  prometheus: ""
  
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    ephemeralStorage: 16Gi
    cpu: 8
    memory: 16Gi
  requests:
    cpu: 200m
    memory: 1Gi
startupProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 10
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 10
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 10

livenessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 10
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 10

fullnameOverride: pcf-perf-info

nodeSelector: {}

tolerations: []

affinity: {}

extraContainers: USE_GLOBAL_VALUE

# Config client configuration
commonCfgClient:
  enabled: true
commonCfgServer:
  # If below parameter is present then it will be used for integrating with config-server.
  # This parameter will be appended with the current release name when deployed with alternate-route
  # In case host name is expected, then leave this parameter blank
  configServerSvcName: occnp-config-mgmt
  host: 10.113.78.180
  port: 8000
  pollingInterval: 5000 #(in ms)
  connectionTimeout: 10000 #(in ms)
commonServiceName: perf-info

overloadManager:
  enabled: false
  ajacentLevelDuration: 10
  ingressGatewaySvcName: occnp-ingress-gateway
  ingressGatewayHost:
  ingressGatewayPort: 80
  ingressGatewayScrapeInterval: 1 #(in s)
  ingressGatewayFailureRateLength: 60
  perfInfoScrapeInterval: 30 #(in s)
  nfType: PCF
  diamGatewayPort: 8000
  calculationInterval: 1000
  publishLoadLevel:
    maxRetryForRemovedService: 2
    forceReportInterval: 1000
    requestTimeout: 5000

probeValidationByPass:
  enabled: false

# Db Hook Configuration
dbConfig:
  dbHost: data-mysql.default
  dbPort: 3306
  configFile: defaultconfig.yaml
  schemaFile: defaultschema.json
  secretName: dbhook-secret
  dbName: commonconfig
  # Name of the Key configured for "DB Username" in Secret with following name: "<dbConfig.secretName>"
  dbUNameLiteral: dbUsername
  # Name of the Key configured for "DB Password" in Secret with following name: "<dbConfig.secretName>"
  dbPwdLiteral: dbPassword
  dbEngine: NDBCLUSTER

dbHookImage:
  name: common_config_hook
  tag: *dbHookImageVersion
  pullPolicy: IfNotPresent

log:
  level:
    perfinfo: WARN
  
gracefulShutdown:
  gracePeriod: 30s
  defaultErrorCode: 503


#The sidecar (istio url) when deployed in serviceMesh
# Default value: http://127.0.0.1:15020/quitquitquit
istioSidecarQuitUrl: ""
# Default value: http://127.0.0.1:15020/ready
istioSidecarReadyUrl: ""
#Enabled when deployed in serviceMesh
serviceMeshCheck: false
# values added to fetch labels from env variable
#Values for CNE 1.8 {tagNamespace: kubernetes_namespace, tagContainerName: container_name, tagServiceName: kubernetes_name}
#Values for CNE 1.9 {tagNamespace: namespace, tagContainerName: container, tagServiceName: service}
tagNamespace: kubernetes_namespace
tagContainerName: container_name
tagServiceName: kubernetes_name

