# Copyright 2022 (C), Oracle and/or its affiliates. All rights reserved.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    {{- include "labels.nonlbServices" . }}
    app.kubernetes.io/component: internal
  annotations:
    {{- include "annotations.nonlbServices" . }}
spec:
  ports:
  - port: {{ .Values.global.nrfauditor.portConfiguration.servicePort }}
    targetPort: {{ .Values.global.nrfauditor.portConfiguration.containerPort }}
    name: http2-internal
  selector:
    app.kubernetes.io/name: {{ template "chart.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
