{{- if .Values.global.performanceServiceEnable }}
{{- if and (has "policy/v1" .Values.global.k8sResources.pdb.supportedVersions) (.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "service-name-perf-info" . }}-v1
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
spec:
  maxUnavailable: {{ template "pdb-max-unavailiable" . }}
  selector:
    matchLabels:
      io.kompose.service: {{ template "perf-info-deployment-name" . }}
{{- else if and (has "policy/v1beta1" .Values.global.k8sResources.pdb.supportedVersions) (.Capabilities.APIVersions.Has "policy/v1beta1/PodDisruptionBudget") }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "service-name-perf-info" . }}-v1beta1
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      io.kompose.service: {{ template "perf-info-deployment-name" . }}
{{- end }}
{{- end }}
