{{- if eq (include "perf-info.createServiceAccount" .) "true" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "perf-info-deployment-name" . }}
  name: {{ template "perf-info-deployment-name" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "perf-info-deployment-name" . }}
  name: {{ template "perf-info-deployment-name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - services
  - events
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - watch
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "perf-info-deployment-name" . }}
  name: {{ template "perf-info-deployment-name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "perf-info-deployment-name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "perf-info-deployment-name" . }}

{{- end }}
