{{- if $.Values.global.alternateRouteServiceEnable }}
{{- if and ( $.Values.global.appinfoServiceEnable) (not .Values.global.serviceAccountName) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "labels.allResources" . }}
  annotations:
    {{- include "annotations.allResources" . }}
  name:  {{ template "alternate-route.rolebinding" . }}-v1
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "alternate-route.serviceaccount" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "alternate-route.role" . }}
{{- end }}
{{- end }}
