{{- if (not .Values.global.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels.allResources" . }}
    app.kubernetes.io/component: egress-front-end
    app:  {{template "chart.fullname" .}}
  annotations:
    {{- include "annotations.allResources" . }}
  name:  {{ template "egressgateway.serviceaccount" .}}
{{- end }}
