{{- if .Values.global.appinfoServiceEnable }}
{{- if and (has "autoscaling/v2" .Values.global.k8sResources.hpat.supportedVersions) (.Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "appinfo-hpa-name" . }}-v2
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "appinfo-deployment-name" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu      
        target:
          type: Utilization
          averageUtilization: {{ .Values.averageCpuUtil }}
{{- else if and (has "autoscaling/v2beta2" .Values.global.k8sResources.hpat.supportedVersions) (.Capabilities.APIVersions.Has "autoscaling/v2beta2/HorizontalPodAutoscaler") }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "appinfo-hpa-name" . }}-v2beta2
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "appinfo-deployment-name" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu      
        target:
          type: Utilization
          averageUtilization: {{ .Values.averageCpuUtil }}
{{- else if and (has "autoscaling/v2beta1" .Values.global.k8sResources.hpat.supportedVersions) (.Capabilities.APIVersions.Has "autoscaling/v2beta1/HorizontalPodAutoscaler") }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "appinfo-hpa-name" . }}-v2beta1
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "appinfo-deployment-name" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.averageCpuUtil }}
{{- else if and (has "autoscaling/v1" .Values.global.k8sResources.hpat.supportedVersions) (.Capabilities.APIVersions.Has "autoscaling/v1/HorizontalPodAutoscaler") }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "appinfo-hpa-name" . }}-v1
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "appinfo-deployment-name" . }}
  targetCPUUtilizationPercentage: {{ .Values.averageCpuUtil }}
{{- end }}
{{- end }}        