{{- if and ( $.Values.global.appinfoServiceEnable) (not .Values.global.serviceAccountName) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels.allResources" . }}
    app: {{ template "appinfo-deployment-name" . }}
  annotations:
    {{- include "annotations.allResources" . }}
  name: {{ template "appinfo-deployment-name" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "labels.allResources" . }}
    app: {{ template "appinfo-deployment-name" . }}
  annotations:
    {{- include "annotations.allResources" . }}
  name: {{ template "appinfo-deployment-name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - endpoints
  - services
  verbs:
  - get
  - watch
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "labels.allResources" . }}
    app: {{ template "appinfo-deployment-name" . }}
  annotations:
    {{- include "annotations.allResources" . }}
  name: {{ template "appinfo-deployment-name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "appinfo-deployment-name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "appinfo-deployment-name" . }}

{{- end }}
